// Add your plugin files here
#include "zVEC3.hpp"
#include "zCModel.hpp"
#include "oCSpell_Data.hpp"
#include "oCSpell_DataManager.hpp"
#include "Spell_Control.hpp"
#include "Spell_Telekinesis.hpp"
#include "Hooks_oCAIHuman.hpp"
#include "Hooks_oCGame.hpp"
#include "Hooks_oCSpawnManager.hpp"
#include "Hooks_oCSpell.hpp"
#include "Hooks_oCTriggerChangeLevel.hpp"
#include "Hooks_oCVisualFX.hpp"
#include "Plugin.hpp"