name: "Build Plugin"

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      version:
        description: "Plugin version"
        required: true
        type: string

      create_release:
        description: "Create GitHub release"
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  plugin:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
          lfs: true

      - name: Set up MSVC
        uses: ./.github/actions/msvc-dev-cmd
        with:
          arch: x86

      - name: Determine version
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ inputs.version }}"
          } else {
            $version = "${{ github.ref_name }}"
          }

          echo "PROJECT_VERSION=$version" >> $env:GITHUB_ENV
          echo "Version: $version"

      - name: Compile plugin
        run: |
          cmake . --preset MP-Release -DPROJECT_VERSION="${{ env.PROJECT_VERSION }}"
          cmake --build --preset MP-Release

      - name: Find plugin
        run: |
          # Find VDF first, fallback to DLL
          $plugin_path = Get-ChildItem -Recurse -Include *.vdf, *.dll -File |
            Sort-Object { $_.Extension -eq ".vdf" } -Descending |
            Select-Object -First 1 -ExpandProperty FullName

          echo "Found plugin path: $plugin_path"

          # Normalize path
          $root = (Resolve-Path ".").Path + "\"
          $plugin_path = $plugin_path.Replace($root, "")
          $plugin_path = $plugin_path.Replace("\", "/")

          echo "plugin_path=$plugin_path" >> $env:GITHUB_ENV

      - name: Upload plugin as artifact
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.create_release }}
        uses: actions/upload-artifact@v7
        with:
          name: plugin-${{ env.PROJECT_VERSION }}
          path: ${{ env.plugin_path }}

      - name: Release Plugin
        if: ${{ github.event_name == 'push' || inputs.create_release }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          body_path: CHANGELOG.md
          files: ${{ env.plugin_path }}
